# Generated by Django 4.1.4 on 2023-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_tata_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tata',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
