# Generated by Django 4.1.4 on 2023-01-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0003_remove_customuser_tata_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Usercus',
        ),
    ]
